// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZd1p2r-9DJaQUQu1iiVG-38XP2PxoM8',
    appId: '1:311245068162:web:4e4ac5719020d50609e19b',
    messagingSenderId: '311245068162',
    projectId: 'dandia-b38ba',
    authDomain: 'dandia-b38ba.firebaseapp.com',
    databaseURL: 'https://dandia-b38ba-default-rtdb.firebaseio.com',
    storageBucket: 'dandia-b38ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0DxcIU20ApGLocfa6tEucmY9pwhZbq80',
    appId: '1:311245068162:android:bd1f757b857ad53609e19b',
    messagingSenderId: '311245068162',
    projectId: 'dandia-b38ba',
    databaseURL: 'https://dandia-b38ba-default-rtdb.firebaseio.com',
    storageBucket: 'dandia-b38ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJy2GPeZogqgu6s8v68QBE7hCyUKN7vQ',
    appId: '1:311245068162:ios:8b80c968b45b0f8609e19b',
    messagingSenderId: '311245068162',
    projectId: 'dandia-b38ba',
    databaseURL: 'https://dandia-b38ba-default-rtdb.firebaseio.com',
    storageBucket: 'dandia-b38ba.appspot.com',
    iosBundleId: 'com.example.dandiaDriver',
  );
}
